//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VA.Gov.Artemis.UI.Text4BabyServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Text4BabyServiceReference.VoxivaSoap")]
    public interface VoxivaSoap {
        
        // CODEGEN: Generating message contract since message InvokeAPIRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeAPI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse InvokeAPI(VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InvokeAPI", ReplyAction="*")]
        System.Threading.Tasks.Task<VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse> InvokeAPIAsync(VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class WorkflowAuthHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private string userIdField;
        
        private string roleIdField;
        
        private string languageIdField;
        
        private string channelIdField;
        
        private string tenantIdField;
        
        private string tenantNameField;
        
        private string applicationIdField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UserId {
            get {
                return this.userIdField;
            }
            set {
                this.userIdField = value;
                this.RaisePropertyChanged("UserId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RoleId {
            get {
                return this.roleIdField;
            }
            set {
                this.roleIdField = value;
                this.RaisePropertyChanged("RoleId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LanguageId {
            get {
                return this.languageIdField;
            }
            set {
                this.languageIdField = value;
                this.RaisePropertyChanged("LanguageId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ChannelId {
            get {
                return this.channelIdField;
            }
            set {
                this.channelIdField = value;
                this.RaisePropertyChanged("ChannelId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TenantId {
            get {
                return this.tenantIdField;
            }
            set {
                this.tenantIdField = value;
                this.RaisePropertyChanged("TenantId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string TenantName {
            get {
                return this.tenantNameField;
            }
            set {
                this.tenantNameField = value;
                this.RaisePropertyChanged("TenantName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ApplicationId {
            get {
                return this.applicationIdField;
            }
            set {
                this.applicationIdField = value;
                this.RaisePropertyChanged("ApplicationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InvokeAPI", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InvokeAPIRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public VA.Gov.Artemis.UI.Text4BabyServiceReference.WorkflowAuthHeader WorkflowAuthHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string batchXML;
        
        public InvokeAPIRequest() {
        }
        
        public InvokeAPIRequest(VA.Gov.Artemis.UI.Text4BabyServiceReference.WorkflowAuthHeader WorkflowAuthHeader, string batchXML) {
            this.WorkflowAuthHeader = WorkflowAuthHeader;
            this.batchXML = batchXML;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="InvokeAPIResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class InvokeAPIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string InvokeAPIResult;
        
        public InvokeAPIResponse() {
        }
        
        public InvokeAPIResponse(string InvokeAPIResult) {
            this.InvokeAPIResult = InvokeAPIResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VoxivaSoapChannel : VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VoxivaSoapClient : System.ServiceModel.ClientBase<VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap>, VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap {
        
        public VoxivaSoapClient() {
        }
        
        public VoxivaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VoxivaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoxivaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VoxivaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap.InvokeAPI(VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest request) {
            return base.Channel.InvokeAPI(request);
        }
        
        public string InvokeAPI(VA.Gov.Artemis.UI.Text4BabyServiceReference.WorkflowAuthHeader WorkflowAuthHeader, string batchXML) {
            VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest inValue = new VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest();
            inValue.WorkflowAuthHeader = WorkflowAuthHeader;
            inValue.batchXML = batchXML;
            VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse retVal = ((VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap)(this)).InvokeAPI(inValue);
            return retVal.InvokeAPIResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse> VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap.InvokeAPIAsync(VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest request) {
            return base.Channel.InvokeAPIAsync(request);
        }
        
        public System.Threading.Tasks.Task<VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIResponse> InvokeAPIAsync(VA.Gov.Artemis.UI.Text4BabyServiceReference.WorkflowAuthHeader WorkflowAuthHeader, string batchXML) {
            VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest inValue = new VA.Gov.Artemis.UI.Text4BabyServiceReference.InvokeAPIRequest();
            inValue.WorkflowAuthHeader = WorkflowAuthHeader;
            inValue.batchXML = batchXML;
            return ((VA.Gov.Artemis.UI.Text4BabyServiceReference.VoxivaSoap)(this)).InvokeAPIAsync(inValue);
        }
    }
}
