object dlgGenetic: TdlgGenetic
  Tag = 1
  Left = 212
  Top = 164
  BorderStyle = bsDialog
  Caption = 'Genetic Screening'
  ClientHeight = 447
  ClientWidth = 707
  Color = clBtnFace
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Arial'
  Font.Style = [fsBold]
  OldCreateOrder = False
  Position = poOwnerFormCenter
  Scaled = False
  OnCreate = FormCreate
  PixelsPerInch = 96
  TextHeight = 14
  object pgBody: TPageControl
    Left = 0
    Top = 0
    Width = 707
    Height = 418
    ActivePage = TabSheet1
    Align = alClient
    Font.Charset = DEFAULT_CHARSET
    Font.Color = clWindowText
    Font.Height = -11
    Font.Name = 'Arial'
    Font.Style = []
    MultiLine = True
    ParentFont = False
    TabOrder = 0
    TabPosition = tpRight
    object TabSheet1: TTabSheet
      Caption = 'Page #1'
      object pnllabels1: TPanel
        Left = 8
        Top = 4
        Width = 146
        Height = 399
        BevelOuter = bvNone
        TabOrder = 56
        object Label2: TLabel
          Tag = 2
          Left = 4
          Top = 39
          Width = 103
          Height = 14
          Caption = 'Neural Tube Defect'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label1: TLabel
          Tag = 1
          Left = 4
          Top = 11
          Width = 70
          Height = 14
          Caption = 'Thalassemia'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label3: TLabel
          Tag = 3
          Left = 4
          Top = 67
          Width = 129
          Height = 14
          Caption = 'Congenital Heart Defect'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ShowAccelChar = False
        end
        object Label4: TLabel
          Tag = 4
          Left = 4
          Top = 95
          Width = 91
          Height = 14
          Caption = 'Down Syndrome'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label5: TLabel
          Tag = 5
          Left = 4
          Top = 123
          Width = 55
          Height = 14
          Caption = 'Tay-Sachs'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label6: TLabel
          Tag = 6
          Left = 4
          Top = 151
          Width = 93
          Height = 14
          Caption = 'Canavan Disease'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label7: TLabel
          Tag = 7
          Left = 4
          Top = 179
          Width = 122
          Height = 14
          Caption = 'Familial Dysautonomia'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label8: TLabel
          Tag = 8
          Left = 4
          Top = 207
          Width = 94
          Height = 14
          Caption = 'Sick Cell Disease'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label9: TLabel
          Tag = 9
          Left = 4
          Top = 235
          Width = 74
          Height = 14
          Caption = 'Sick Cell Trait'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label10: TLabel
          Tag = 10
          Left = 4
          Top = 263
          Width = 61
          Height = 14
          Caption = 'Hemophilia'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label11: TLabel
          Tag = 11
          Left = 4
          Top = 291
          Width = 89
          Height = 14
          Caption = 'Blood Disorders'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label12: TLabel
          Tag = 12
          Left = 4
          Top = 319
          Width = 110
          Height = 14
          Caption = 'Muscular Dystrophy'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label13: TLabel
          Tag = 13
          Left = 4
          Top = 347
          Width = 82
          Height = 14
          Caption = 'Cystic Fibrosis'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label14: TLabel
          Tag = 14
          Left = 4
          Top = 375
          Width = 113
          Height = 14
          Caption = 'Huntington'#39's Chorea'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
      end
      object CheckBox1: TCheckBox
        Tag = 1
        Left = 164
        Top = 15
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        OnClick = CheckBoxClick
      end
      object CheckBox2: TCheckBox
        Tag = 1
        Left = 210
        Top = 15
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = CheckBoxClick
      end
      object CheckBox3: TCheckBox
        Tag = 1
        Left = 256
        Top = 15
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        OnClick = CheckBoxClick
      end
      object CheckBox4: TCheckBox
        Tag = 2
        Left = 164
        Top = 43
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        OnClick = CheckBoxClick
      end
      object CheckBox5: TCheckBox
        Tag = 2
        Left = 210
        Top = 43
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        OnClick = CheckBoxClick
      end
      object CheckBox6: TCheckBox
        Tag = 2
        Left = 256
        Top = 43
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        OnClick = CheckBoxClick
      end
      object CheckBox7: TCheckBox
        Tag = 3
        Left = 164
        Top = 71
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        OnClick = CheckBoxClick
      end
      object CheckBox8: TCheckBox
        Tag = 3
        Left = 210
        Top = 71
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        OnClick = CheckBoxClick
      end
      object CheckBox9: TCheckBox
        Tag = 3
        Left = 256
        Top = 71
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 10
        OnClick = CheckBoxClick
      end
      object CheckBox10: TCheckBox
        Tag = 4
        Left = 164
        Top = 99
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 12
        OnClick = CheckBoxClick
      end
      object CheckBox11: TCheckBox
        Tag = 4
        Left = 210
        Top = 99
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 13
        OnClick = CheckBoxClick
      end
      object CheckBox12: TCheckBox
        Tag = 4
        Left = 256
        Top = 99
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 14
        OnClick = CheckBoxClick
      end
      object CheckBox13: TCheckBox
        Tag = 5
        Left = 164
        Top = 127
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 16
        OnClick = CheckBoxClick
      end
      object CheckBox14: TCheckBox
        Tag = 5
        Left = 210
        Top = 127
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 17
        OnClick = CheckBoxClick
      end
      object CheckBox15: TCheckBox
        Tag = 5
        Left = 256
        Top = 127
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 18
        OnClick = CheckBoxClick
      end
      object CheckBox16: TCheckBox
        Tag = 6
        Left = 164
        Top = 155
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 20
        OnClick = CheckBoxClick
      end
      object CheckBox17: TCheckBox
        Tag = 6
        Left = 210
        Top = 155
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 21
        OnClick = CheckBoxClick
      end
      object CheckBox18: TCheckBox
        Tag = 6
        Left = 256
        Top = 155
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 22
        OnClick = CheckBoxClick
      end
      object CheckBox19: TCheckBox
        Tag = 7
        Left = 164
        Top = 183
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 24
        OnClick = CheckBoxClick
      end
      object CheckBox20: TCheckBox
        Tag = 7
        Left = 210
        Top = 183
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 25
        OnClick = CheckBoxClick
      end
      object CheckBox21: TCheckBox
        Tag = 7
        Left = 256
        Top = 183
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 26
        OnClick = CheckBoxClick
      end
      object CheckBox22: TCheckBox
        Tag = 8
        Left = 164
        Top = 211
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 28
        OnClick = CheckBoxClick
      end
      object CheckBox23: TCheckBox
        Tag = 8
        Left = 210
        Top = 211
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 29
        OnClick = CheckBoxClick
      end
      object CheckBox24: TCheckBox
        Tag = 8
        Left = 256
        Top = 211
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 30
        OnClick = CheckBoxClick
      end
      object CheckBox25: TCheckBox
        Tag = 9
        Left = 164
        Top = 239
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 32
        OnClick = CheckBoxClick
      end
      object CheckBox26: TCheckBox
        Tag = 9
        Left = 210
        Top = 239
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 33
        OnClick = CheckBoxClick
      end
      object CheckBox27: TCheckBox
        Tag = 9
        Left = 256
        Top = 239
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 34
        OnClick = CheckBoxClick
      end
      object CheckBox28: TCheckBox
        Tag = 10
        Left = 164
        Top = 267
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 36
        OnClick = CheckBoxClick
      end
      object CheckBox29: TCheckBox
        Tag = 10
        Left = 210
        Top = 267
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 37
        OnClick = CheckBoxClick
      end
      object CheckBox30: TCheckBox
        Tag = 10
        Left = 256
        Top = 267
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 38
        OnClick = CheckBoxClick
      end
      object CheckBox31: TCheckBox
        Tag = 11
        Left = 164
        Top = 295
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 40
        OnClick = CheckBoxClick
      end
      object CheckBox32: TCheckBox
        Tag = 11
        Left = 210
        Top = 295
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 41
        OnClick = CheckBoxClick
      end
      object CheckBox33: TCheckBox
        Tag = 11
        Left = 256
        Top = 295
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 42
        OnClick = CheckBoxClick
      end
      object CheckBox34: TCheckBox
        Tag = 12
        Left = 164
        Top = 323
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 44
        OnClick = CheckBoxClick
      end
      object CheckBox35: TCheckBox
        Tag = 12
        Left = 210
        Top = 323
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 45
        OnClick = CheckBoxClick
      end
      object CheckBox36: TCheckBox
        Tag = 12
        Left = 256
        Top = 323
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 46
        OnClick = CheckBoxClick
      end
      object CheckBox37: TCheckBox
        Tag = 13
        Left = 164
        Top = 351
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 48
        OnClick = CheckBoxClick
      end
      object CheckBox38: TCheckBox
        Tag = 13
        Left = 210
        Top = 351
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 49
        OnClick = CheckBoxClick
      end
      object CheckBox39: TCheckBox
        Tag = 13
        Left = 256
        Top = 351
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 50
        OnClick = CheckBoxClick
      end
      object CheckBox40: TCheckBox
        Tag = 14
        Left = 164
        Top = 379
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 52
        OnClick = CheckBoxClick
      end
      object CheckBox41: TCheckBox
        Tag = 14
        Left = 210
        Top = 379
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 53
        OnClick = CheckBoxClick
      end
      object CheckBox42: TCheckBox
        Tag = 14
        Left = 256
        Top = 379
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 54
        OnClick = CheckBoxClick
      end
      object Edit1: TEdit
        Tag = 1
        Left = 328
        Top = 12
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 3
      end
      object Edit2: TEdit
        Tag = 2
        Left = 328
        Top = 40
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 7
      end
      object Edit3: TEdit
        Tag = 3
        Left = 328
        Top = 68
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 11
      end
      object Edit4: TEdit
        Tag = 4
        Left = 328
        Top = 96
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 15
      end
      object Edit5: TEdit
        Tag = 5
        Left = 328
        Top = 124
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 19
      end
      object Edit6: TEdit
        Tag = 6
        Left = 328
        Top = 152
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 23
      end
      object Edit7: TEdit
        Tag = 7
        Left = 328
        Top = 180
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 27
      end
      object Edit8: TEdit
        Tag = 8
        Left = 328
        Top = 208
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 31
      end
      object Edit9: TEdit
        Tag = 9
        Left = 328
        Top = 236
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 35
      end
      object Edit10: TEdit
        Tag = 10
        Left = 328
        Top = 264
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 39
      end
      object Edit11: TEdit
        Tag = 11
        Left = 328
        Top = 292
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 43
      end
      object Edit12: TEdit
        Tag = 12
        Left = 328
        Top = 320
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 47
      end
      object Edit13: TEdit
        Tag = 13
        Left = 328
        Top = 348
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 51
      end
      object Edit14: TEdit
        Tag = 14
        Left = 328
        Top = 376
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 55
      end
    end
    object TabSheet2: TTabSheet
      Caption = 'Page #2'
      object CheckBox43: TCheckBox
        Tag = 15
        Left = 164
        Top = 15
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 0
        OnClick = CheckBoxClick
      end
      object CheckBox53: TCheckBox
        Tag = 18
        Left = 164
        Top = 161
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 12
        OnClick = CheckBoxClick
      end
      object CheckBox54: TCheckBox
        Tag = 15
        Left = 210
        Top = 15
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 1
        OnClick = CheckBoxClick
      end
      object CheckBox55: TCheckBox
        Tag = 18
        Left = 210
        Top = 161
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 13
        OnClick = CheckBoxClick
      end
      object CheckBox56: TCheckBox
        Tag = 18
        Left = 256
        Top = 161
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 14
        OnClick = CheckBoxClick
      end
      object CheckBox57: TCheckBox
        Tag = 19
        Left = 164
        Top = 215
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 16
        OnClick = CheckBoxClick
      end
      object CheckBox58: TCheckBox
        Tag = 19
        Left = 210
        Top = 215
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 17
        OnClick = CheckBoxClick
      end
      object CheckBox59: TCheckBox
        Tag = 19
        Left = 256
        Top = 215
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 18
        OnClick = CheckBoxClick
      end
      object CheckBox60: TCheckBox
        Tag = 20
        Left = 164
        Top = 272
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 20
        OnClick = CheckBoxClick
      end
      object CheckBox61: TCheckBox
        Tag = 20
        Left = 210
        Top = 272
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 21
        OnClick = CheckBoxClick
      end
      object CheckBox62: TCheckBox
        Tag = 20
        Left = 256
        Top = 272
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 22
        OnClick = CheckBoxClick
      end
      object CheckBox65: TCheckBox
        Tag = 15
        Left = 256
        Top = 15
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 2
        OnClick = CheckBoxClick
      end
      object CheckBox76: TCheckBox
        Tag = 16
        Left = 164
        Top = 43
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 4
        OnClick = CheckBoxClick
      end
      object CheckBox80: TCheckBox
        Tag = 16
        Left = 210
        Top = 43
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 5
        OnClick = CheckBoxClick
      end
      object CheckBox81: TCheckBox
        Tag = 16
        Left = 256
        Top = 43
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 6
        OnClick = CheckBoxClick
      end
      object CheckBox82: TCheckBox
        Tag = 17
        Left = 164
        Top = 99
        Width = 40
        Height = 17
        Caption = 'Yes'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 8
        OnClick = CheckBoxClick
      end
      object CheckBox83: TCheckBox
        Tag = 17
        Left = 210
        Top = 99
        Width = 40
        Height = 17
        Caption = 'No'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 9
        OnClick = CheckBoxClick
      end
      object CheckBox84: TCheckBox
        Tag = 17
        Left = 256
        Top = 99
        Width = 71
        Height = 17
        Caption = 'Unknown'
        Font.Charset = DEFAULT_CHARSET
        Font.Color = clWindowText
        Font.Height = -11
        Font.Name = 'Arial'
        Font.Style = []
        ParentFont = False
        TabOrder = 10
        OnClick = CheckBoxClick
      end
      object Edit15: TEdit
        Tag = 15
        Left = 328
        Top = 12
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 3
      end
      object Edit21: TEdit
        Tag = 16
        Left = 328
        Top = 40
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 7
      end
      object Edit22: TEdit
        Tag = 17
        Left = 328
        Top = 96
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 11
      end
      object Edit26: TEdit
        Tag = 19
        Left = 328
        Top = 212
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 19
      end
      object Edit28: TEdit
        Tag = 20
        Left = 328
        Top = 269
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 23
      end
      object pnlLabels2: TPanel
        Left = 8
        Top = 4
        Width = 146
        Height = 406
        BevelOuter = bvNone
        TabOrder = 24
        object Label15: TLabel
          Tag = 16
          Left = 4
          Top = 39
          Width = 40
          Height = 14
          Caption = 'Autism'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label16: TLabel
          Tag = 15
          Left = 4
          Top = 11
          Width = 103
          Height = 14
          Caption = 'Mental Retardation'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
        end
        object Label17: TLabel
          Tag = 17
          Left = 4
          Top = 67
          Width = 133
          Height = 70
          Caption = 
            'Chromosomal Disorder Includes any inherited genetic or chromosom' +
            'al disorders '
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          ShowAccelChar = False
          WordWrap = True
        end
        object Label21: TLabel
          Tag = 18
          Left = 4
          Top = 151
          Width = 107
          Height = 28
          Caption = 'Maternal Metabolic Disorder'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          WordWrap = True
        end
        object Label23: TLabel
          Tag = 19
          Left = 4
          Top = 193
          Width = 133
          Height = 56
          Caption = 
            'Dysmorphism (Birth Defect) Patient or baby'#39's father has a child ' +
            'with birth defects'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          WordWrap = True
        end
        object Label24: TLabel
          Tag = 20
          Left = 4
          Top = 263
          Width = 119
          Height = 28
          Caption = 'Recurrent pregnancy loss/stillbirth'
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -11
          Font.Name = 'Arial'
          Font.Style = [fsBold]
          ParentFont = False
          WordWrap = True
        end
      end
      object Edit23: TEdit
        Tag = 18
        Left = 328
        Top = 158
        Width = 337
        Height = 22
        Enabled = False
        TabOrder = 15
      end
    end
  end
  object pnlfooter: TPanel
    Tag = 19641
    Left = 0
    Top = 418
    Width = 707
    Height = 29
    Align = alBottom
    BevelOuter = bvNone
    TabOrder = 1
    object btnOK: TBitBtn
      Left = 550
      Top = 3
      Width = 75
      Height = 25
      Align = alCustom
      Anchors = [akTop, akRight]
      Kind = bkOK
      NumGlyphs = 2
      TabOrder = 1
      OnClick = btnOKClick
    end
    object btnCancel: TBitBtn
      Left = 631
      Top = 3
      Width = 75
      Height = 25
      Align = alCustom
      Anchors = [akTop, akRight]
      Kind = bkCancel
      NumGlyphs = 2
      TabOrder = 2
    end
    object btnNeg: TBitBtn
      Left = 2
      Top = 3
      Width = 96
      Height = 25
      Align = alCustom
      Caption = 'Negative for all'
      Default = True
      Font.Charset = DEFAULT_CHARSET
      Font.Color = clWindowText
      Font.Height = -11
      Font.Name = 'Arial'
      Font.Style = [fsUnderline]
      NumGlyphs = 2
      ParentFont = False
      TabOrder = 0
      OnClick = btnNegClick
    end
  end
end
